import Navbar from "@/components/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Certificate | PHONGPHAT",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <Navbar route_id={3} />
        </>
    )
}