import type { Metadata } from "next";
import { Kanit, Nunito } from 'next/font/google'
import "./globals.css";

const kanitFont = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-kanit",
})

const nunitoFont = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-nunito",
})

export const metadata: Metadata = {
  title: "Portfolio. | PHONGPHAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${kanitFont.variable} ${nunitoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
